import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
padding = { x = 8, y = 8 }
# opacity = 0.8

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 12
offset = { x = 0, y = 1 }

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
